/*
 MIT License (c) copyright B Cavalier & J Hann */
typeof $sf=="undefined"&&($sf={});if(typeof $sf.env=="undefined")$sf.env="prod";$sf.env_cdn="wsimg.com";$sf.proto="https:"==document.location.protocol?"https:":"http:";if(typeof $sf.plabel=="undefined")$sf.plabel=1;if(typeof $sf.skin=="undefined")$sf.skin="app";if(typeof $sf.culture=="undefined")$sf.culture="en";if(typeof $sf.preload=="undefined")$sf.preload=1;if(typeof $sf.getjQuery=="undefined")$sf.getjQuery=function(){return window.jQuery};if(typeof $sf.require=="undefined")$sf.require={};
if(typeof $sf.require.js_root=="undefined")$sf.require.js_root=$sf.proto+"//img4."+$sf.env_cdn;if(typeof $sf.require.jquery=="undefined")$sf.require.jquery=$sf.proto+"//img4.wsimg.com/starfield/jquery/v1.7.1/jquery.js";if(typeof $sf.require.css_root=="undefined")$sf.require.css_root=$sf.proto+"//img2."+$sf.env_cdn;$sf.require.core=$sf.require.js_root+"/starfield/sf.core/v1.5.2/sf.core";$sf.require.core_css=$sf.require.css_root+"/starfield/sf.core/v1.5.2/sf.core.css";
var c={pluginPath:$sf.require.js_root+"/starfield/curl/v0.5.3/plugin",paths:{"starfield/jquery.mod":$sf.require.jquery,"starfield/sf.core.pkg":$sf.require.core,"css!starfield/sf.core.css":$sf.require.core_css,"css!starfield/sf.fos.core.0.css":$sf.require.core_css.replace("sf.core.css","sf.fos.core.0.css"),"css!starfield/sf.fos.core.1.css":$sf.require.core_css.replace("sf.core.css","sf.fos.core.1.css"),"css!starfield/sf.fos.core.2.css":$sf.require.core_css.replace("sf.core.css","sf.fos.core.2.css"),
"css!starfield/sf.fos.core.1387.css":$sf.require.core_css.replace("sf.core.css","sf.fos.core.1387.css"),"css!":$sf.require.css_root,"link!":$sf.require.css_root},apiName:"require"};if(typeof $sf.baseUrl=="string")c.baseUrl=$sf.baseUrl;if(typeof $sf.debug!="undefined")c.debug=$sf.debug;
c.addModules=function(i){for(var g=0;g<i.length;g++){var b=i[g];typeof b=="string"?c.paths["starfield/"+b]=$sf.require.core:(c.paths["starfield/"+b.name]=$sf.require.js_root+"/starfield/"+b.name+"/v"+b.version+"/"+b.name,c.paths["css!starfield/"+b.name+".css"]=$sf.require.css_root+"/starfield/"+b.name+"/v"+b.version+"/"+b.name+".css")}};
c.addModules(["sf.growl","sf.tabs","sf.dialog","sf.tipper","sf.pagehelp","sf.alerts","sf.validator","sf.msg.overlay",{name:"sf.zoom",version:"0.2"},{name:"sf.share",version:"1.1.2"},{name:"sf.flyout",version:"0.5.4"},{name:"sf.datepicker",version:"0.7.2"},{name:"sf.colorpicker",version:"0.3.5"},{name:"sf.tourguide",version:"0.1.5"},{name:"sf.context",version:"0.1.2"},{name:"sf.pagewizard",version:"0.1"},{name:"sf.datagrid",version:"0.1"}]);
if(typeof $sf.require.paths==="object")for(p in $sf.require.paths)c.paths[p]=$sf.require.paths[p];window.curl=c;
(function(i){function g(){}function b(a,d){return C.call(a).indexOf("[object "+d)==0}function j(a){return a&&a.charAt(a.length-1)=="/"?a.substr(0,a.length-1):a}function w(a,d){var f,l,h;l=1;a=a.replace(F,function(a,d,f){f&&l++;h=!0;return""});return h?(f=d.split("/"),f.splice(f.length-l,l),f.concat(a||[]).join("/")):a}function v(a){var d=a.indexOf("!");return{resourceId:a.substr(d+1),pluginId:d>=0&&a.substr(0,d)}}function A(){}function y(a){A.prototype=a;a=new A;A.prototype=n;return a}function s(){function a(a,
d,f){l.push([a,d,f])}function d(a,d){for(var f,h=0;f=l[h++];)(f=f[a])&&f(d)}var f,l,h;f=this;l=[];h=function(f,e){a=f?function(a){a&&a(e)}:function(a,d){d&&d(e)};h=g;d(f?0:1,e);d=g;l=t};this.then=function(d,l,h){a(d,l,h);return f};this.resolve=function(a){f.resolved=a;h(!0,a)};this.reject=function(a){f.rejected=a;h(!1,a)};this.progress=function(a){d(2,a)}}function o(a,d,f,l){return a instanceof s?a.then(d,f,l):d(a)}function r(a,d,f){return function(){var l;--a>=0&&d&&(l=d.apply(t,arguments));a==0&&
f&&f(l);return l}}function x(){function a(d,f,h){var b;b=m.createContext(e,t,[].concat(d));this.then=d=function(a,d){o(b,function(d){a&&a.apply(t,d)},function(a){if(d)d(a);else throw a;});return this};this.next=function(d,f){return new a(d,f,b)};f&&d(f);o(h,function(){m.getDeps(b)})}var d=[].slice.call(arguments);b(d[0],"Object")&&(e=m.extractCfg(d.shift()),m.checkPreloads(e));return new a(d[0],d[1])}function D(a){var d=a.id;if(d==t)if(f!==t)f={ex:"Multiple anonymous defines in url"};else if(!(d=
m.getCurrentDefName()))f=a;if(d!=t){var b=u[d];if(!(d in u))b=m.resolvePathInfo(d,e).config,b=u[d]=m.createResourceDef(b,d);if(b instanceof s)b.useNet=!1,m.defineResource(b,a)}}var e=i.curl,E=i.document,I=E&&(E.head||E.getElementsByTagName("head")[0]),B={},z={},K={},J={},n={},C=n.toString,t,G={loaded:1,interactive:K,complete:1},u={},H=!1,f,q=/\?/,k=/^\/|^[^:]+:\/\//,F=/(?:^|\/)(\.)(\.?)\/?/g,N=/\/\*[\s\S]*?\*\/|(?:[^\\])\/\/.*?[\n\r]/g,O=/require\s*\(\s*["']([^"']+)["']\s*\)|(?:[^\\]?)(["'])/g,L,
m;m={createContext:function(a,d,f,l){function h(a){return w(a,k.ctxId)}function e(d,f){var l,q,g,j;l=f&&function(a){f.apply(t,a)};if(b(d,"String")){q=h(d);g=u[q];j=g instanceof s&&g.exports;if(!(q in u))throw Error("Module not resolved: "+q);if(l)throw Error("require(id, callback) not allowed");return j||g}else o(m.getDeps(m.createContext(a,k.id,d)),l)}var k;k=new s;k.ctxId=k.id=d||"";k.isPreload=l;k.depNames=f;k.require=e;e.toUrl=function(d){return m.resolvePathInfo(h(d),a).url};k.toAbsId=h;return k},
createResourceDef:function(a,d,f,l){var h,e,b,k;h=m.createContext(a,d,t,f);h.ctxId=l==t?d:l;e=h.resolve;b=r(1,function(a){h.deps=a;try{k=m.executeDefFunc(h)}catch(d){h.reject(d)}});h.resolve=function(a){b(a);u[h.id]=k;e(k)};h.exportsReady=function(a){h.exports&&(b(a),h.progress(z))};return h},createPluginDef:function(a,d,f,l){a=m.createContext(a,d,t,f);a.ctxId=l;return a},getCjsRequire:function(a){return a.require},getCjsExports:function(a){return a.exports||(a.exports={})},getCjsModule:function(a){var d=
a.module;if(!d)d=a.module={id:a.id,uri:m.getDefUrl(a),exports:m.getCjsExports(a)},d.exports=d.exports;return d},getDefUrl:function(a){return a.url||(a.url=m.checkToAddJsExt(a.require.toUrl(a.id)))},extractCfg:function(a){function d(d,f){var e,h,b,k,q;for(q in d){b=d[q];k=a;h=v(j(b.id||b.name||q));e=h.resourceId;if(h=h.pluginId){k=l[h];if(!k)k=l[h]=y(a),k.pathMap=y(a.pathMap),k.pathList=[];delete d[q]}if(f){h=b;var g=void 0,i=void 0,g=h.path=j(h.path||h.location||""),i=h.main||"main";h.config=h.config;
h.main=i.charAt(0)=="."?j(w(i,g)):j(g)+"/"+i}else h={path:j(b)};h.specificity=e.split("/").length;e?(k.pathMap[e]=h,k.pathList.push(e)):k.baseUrl=m.resolveUrl(b,a)}}function f(a){var d=a.pathMap;a.pathRx=RegExp("^("+a.pathList.sort(function(a,f){return d[a].specificity<d[f].specificity}).join("|").replace(/\//g,"\\/")+")(?=\\/|$)");delete a.pathList}var l;a.baseUrl=a.baseUrl||"";a.pluginPath="pluginPath"in a?a.pluginPath:"curl/plugin";a.pathMap={};l=a.plugins=a.plugins||{};a.pathList=[];d(a.paths,
!1);d(a.packages,!0);for(var h in l){var e=l[h].pathList;if(e)l[h].pathList=e.concat(a.pathList),f(l[h])}f(a);return a},checkPreloads:function(a){var d;(d=a.preloads)&&d.length>0&&o(H,function(){H=m.getDeps(m.createContext(a,t,d,!0))})},resolvePathInfo:function(a,d,f){var l,h,b;l=d.pathMap;f&&d.pluginPath&&a.indexOf("/")<0&&!(a in l)&&(a=j(d.pluginPath)+"/"+a);f=k.test(a)?a:a.replace(d.pathRx,function(d){h=l[d]||{};b=h.config;return h.main&&d==a?h.main:h.path||""});return{path:f,config:b||e,url:m.resolveUrl(f,
d)}},resolveUrl:function(a,d){var f=d.baseUrl;return f&&!k.test(a)?j(f)+"/"+a:a},checkToAddJsExt:function(a){return a+(q.test(a)?"":".js")},loadScript:function(a,d,f){var l=E.createElement("script");l.onload=l.onreadystatechange=function(f){f=f||i.event;if(f.type=="load"||G[l.readyState])delete J[a.id],l.onload=l.onreadystatechange=l.onerror="",d()};l.onerror=function(){f(Error("Syntax or http error: "+a.url))};l.charset="utf-8";l.async=!0;l.src=a.url;J[a.id]=l;I.insertBefore(l,I.firstChild)},extractCjsDeps:function(a){var d=
[],f;(typeof a=="string"?a:a.toSource?a.toSource():a.toString()).replace(N,"").replace(O,function(a,h,e){e?f=f==e?t:f:f||d.push(h);return a});return d},fixArgs:function(a){var d,f,e,h,k,q;k=a.length;e=a[k-1];h=b(e,"Function")?e.length:-1;k==2?b(a[0],"Array")?f=a[0]:d=a[0]:k==3&&(d=a[0],f=a[1]);!f&&h>0&&(q=!0,f=["require","exports","module"].slice(0,h).concat(m.extractCjsDeps(e)));return{id:d,deps:f||[],res:h>=0?e:function(){return e},cjs:q}},executeDefFunc:function(a){var d;d=a.res.apply(a.cjs?a.exports:
t,a.deps);if(d===t&&a.exports)d=a.module?a.exports=a.module.exports:a.exports;return d},defineResource:function(a,d){o(a.isPreload||H,function(){a.res=d.res;a.cjs=d.cjs;a.depNames=d.deps;m.getDeps(a)})},getDeps:function(a){function d(a,d,f){b[d]=a;f&&i(a,d)}function f(d,e){var h,k,b,l;h=r(1,function(a){k(a);j(a,e)});k=r(1,function(a){i(a,e)});b=m.fetchDep(d,a);(l=b instanceof s&&b.exports)&&k(l);o(b,h,a.reject,a.exports&&function(a){b.exports&&(a==B?k(b.exports):a==z&&h(b.exports))})}function e(){a.resolve(b)}
var h,k,b,q,g,i,j;b=[];k=a.depNames;q=k.length;k.length==0&&e();i=r(q,d,function(){a.exportsReady&&a.exportsReady(b)});j=r(q,d,e);for(h=0;h<q;h++)g=k[h],g in L?(j(L[g](a),h,!0),a.exports&&a.progress(B)):g?f(g,h):j(t,h,!0);return a},fetchResDef:function(a){m.getDefUrl(a);m.loadScript(a,function(){var d=f;f=t;a.useNet!==!1&&(!d||d.ex?a.reject(Error((d&&d.ex||"define() missing or duplicated: url").replace("url",a.url))):m.defineResource(a,d))},a.reject);return a},fetchDep:function(a,d){var f,b,k,q,g,
j,i,z,F,n;f=d.toAbsId;b=d.isPreload;k=v(a);j=k.resourceId;q=f(k.pluginId||j);i=m.resolvePathInfo(q,e,!!k.pluginId);if(k.pluginId)g=q;else if(g=i.config.moduleLoader)j=q,q=g,i=m.resolvePathInfo(g,e);z=u[q];if(!(q in u))z=u[q]=m.createResourceDef(i.config,q,b,k.pluginId?i.path:t),z.url=m.checkToAddJsExt(i.url),m.fetchResDef(z);q==g&&(F=new s,n=e.plugins[g]||e,o(z,function(a){var d,k,e;e=a.dynamic;j="normalize"in a?a.normalize(j,f,n)||"":f(j);k=g+"!"+j;d=u[k];if(!(k in u)){d=m.createPluginDef(n,k,b,
j);e||(u[k]=d);var h=function(a){d.resolve(a);e||(u[k]=a)};h.resolve=h;h.reject=d.reject;a.load(j,d.require,h,n)}F!=d&&o(d,F.resolve,F.reject,F.progress)},F.reject));return F||z},getCurrentDefName:function(){var a;if(!b(i.opera,"Opera"))for(var d in J)if(G[J[d].readyState]==K){a=d;break}return a}};L={require:m.getCjsRequire,exports:m.getCjsExports,module:m.getCjsModule};if(!b(e,"Function")){e=m.extractCfg(e||{});m.checkPreloads(e);var M;(e.apiContext||i)[e.apiName||"curl"]=x;u.curl=x;M=i.define=function(){var a=
m.fixArgs(arguments);D(a)};x.version="0.6.2";M.amd={plugins:!0,jQuery:!0,curl:"0.6.2"};u["curl/_privileged"]={core:m,cache:u,cfg:e,_define:D,_curl:x,Promise:s}}})(this);
(function(i,g){function b(){if(!g.body)return!1;B||(B=g.createTextNode(""));try{return g.body.removeChild(g.body.appendChild(B)),B=I,!0}catch(e){return!1}}function j(){var j;j=A[g[v]]&&b();if(!o&&j){o=!0;for(clearTimeout(E);D=e.pop();)D();s&&(g[v]="complete");for(var i;i=y.shift();)i()}return j}function w(){j();o||(E=setTimeout(w,r))}var v="readyState",A={loaded:1,interactive:1,complete:1},y=[],s=g&&typeof g[v]!="string",o=!1,r=10,x,D,e=[],E,I,B;x="addEventListener"in i?function(e,b){e.addEventListener(b,
j,!1);return function(){e.removeEventListener(b,j,!1)}}:function(e,b){e.attachEvent("on"+b,j);return function(){e.detachEvent(b,j)}};g&&!j()&&(e=[x(i,"load"),x(g,"readystatechange"),x(i,"DOMContentLoaded")],E=setTimeout(w,r));define("curl/domReady",function(){function e(b){o?b():y.push(b)}e.then=e;e.amd=!0;return e})})(this,this.document);define("domReady",["curl/domReady"],function(i){return{load:function(g,b,j){i(j)}}});
define("async",function(){return{load:function(i,g,b){function j(g){typeof b.resolve=="function"?b.resolve(g):b(g)}function w(g){typeof b.reject=="function"&&b.reject(g)}g([i],function(b){typeof b.then=="function"?b.then(function(g){arguments.length==0&&(g=b);j(g)},w):j(b)})},analyze:function(i,g,b){b(i)}}});
(function(i,g){function b(e,b,j){function B(g){g=g||i.event;if(g.type=="load"||s[n.readyState]){n.onload=n[o]=n.onerror="";if(e.exports)e.resolved=w(e.exports);!e.exports||e.resolved?b(n):z()}}function z(){n.onload=n[o]=n.onerror="";j&&j(Error("Script error or http error: "+e.url))}function x(){n.onload&&s[n.readyState]?B({}):n.onload&&v<new Date?z():setTimeout(x,10)}var v,n;v=(new Date).valueOf()+(e.timeoutMsec||300)*1E3;n=g.createElement("script");j&&e.exports&&setTimeout(x,10);n.type=e.mimetype||
"text/javascript";n.onload=n[o]=B;n.onerror=z;n.charset=e.charset||"utf-8";n.async=!e.order;n.src=e.url;r.insertBefore(n,r.firstChild)}function j(e,g){b(e,function(){var b=A.shift();x=A.length>0;b&&j.apply(null,b);g.resolve(e.resolved||!0)},function(b){g.reject(b)})}function w(b){try{return eval("global."+b)}catch(g){return D}}var v={},A=[],y=g&&g.createElement("script").async==!0,s={loaded:1,interactive:1,complete:1},o="onreadystatechange",r=g&&(g.head||g.getElementsByTagName("head")[0]),x,D;define("js",
{dynamic:!0,load:function(e,g,i,o){var r,s,w,n;r=e.indexOf("!order")>0;s=e.indexOf("!exports=");w=s>0&&e.substr(s+9);n="prefetch"in o?o.prefetch:!0;e=r||s>0?e.substr(0,e.indexOf("!")):e;if(e in v)i(v[e]);else if(v[e]=D,g={name:e,url:g.toUrl(e.lastIndexOf(".")<=e.lastIndexOf("/")?e+".js":e),order:r,exports:w,timeoutMsec:o.timeout},o={resolve:function(b){v[e]=b;(i.resolve||i)(b)},reject:i.reject||function(b){throw b;}},r&&!y&&x){if(A.push([g,o]),n)g.mimetype="text/cache",b(g,function(b){b.parentNode.removeChild(b)},
!1),g.mimetype=""}else x=x||r,j(g,o)}})})(this,this.document);
(function(i){function g(f,b){var k=f.link;k[D]=k[e]=function(){if(!k.readyState||k.readyState=="complete")K["event-link-onload"]=!0,y(f),b()}}function b(f){for(var f=f.split("!"),b,e=1;b=f[e++];)b=b.split("=",2),f[b[0]]=b.length==2?b[1]:!0;return f}function j(f,b){if(document.createStyleSheet){if(document.styleSheets.length>=30){for(var e=document.styleSheets.length-29,g=[],i=document.getElementsByTagName("link"),n=0;g.length<=e&&n<i.length;){var o=i[n];o.getAttribute("_curl_movable")&&o.type==="text/css"&&
(g.push(o.href),o.parentNode&&o.parentNode.removeChild(o));n++}if(g.length==e){G||(G=document.createStyleSheet());s();for(vi=0;n<=g.length;n++)j(f,g[n])}}G||(G=document.createStyleSheet());document.styleSheets.length>=30&&s()}e=f[E]("link");e.rel="stylesheet";e.type="text/css";e.setAttribute("_curl_movable",!0);if(b)e.href=b;return e}function w(f){var b,e,g=!1;try{if(b=f.sheet||f.styleSheet,(g=(e=b.cssRules||b.rules)?e.length>0:e!==B)&&{}.toString.call(window.chrome)=="[object Chrome]"){b.insertRule("#_cssx_load_test{margin-top:-5px;}",
0);if(!u)u=C[E]("div"),u.id="_cssx_load_test",t.appendChild(u);g=C.defaultView.getComputedStyle(u,null).marginTop=="-5px";b.deleteRule(0)}}catch(j){g=j.code==1E3||j.message.match(/security|denied/i)}return g}function v(f,b){w(f.link)?(y(f),b()):I||setTimeout(function(){v(f,b)},f.wait)}function A(f,b){function e(){j||(j=!0,b())}var j;g(f,e);K["event-link-onload"]||v(f,e)}function y(f){f=f.link;f[D]=f[e]=null}function s(){var f,b,e,g=0;e=G;G=null;for(b=document.getElementsByTagName("link");f=b[g];)f.getAttribute("_curl_movable")?
(e.addImport(f.href),f.parentNode&&f.parentNode.removeChild(f)):g++}function o(b,e){return b.replace(n,function(b,f){var g=f;J.test(g)||(g=e+g);return'url("'+g+'")'})}function r(b){clearTimeout(r.debouncer);r.accum?r.accum.push(b):(r.accum=[b],H=C.createStyleSheet?C.createStyleSheet():t.appendChild(C.createElement("style")));r.debouncer=setTimeout(function(){var b,f;b=H;H=B;f=r.accum.join("\n");r.accum=B;f=f.replace(/.+charset[^;]+;/g,"");"cssText"in b?b.cssText=f:b.appendChild(C.createTextNode(f))},
0);return H}function x(b){return{cssRules:function(){return b.cssRules||b.rules},insertRule:b.insertRule||function(e,g){var j=e.split(/\{|\}/g);b.addRule(j[0],j[1],g);return g},deleteRule:b.deleteRule||function(e){b.removeRule(e);return e},sheet:function(){return b}}}var D="onreadystatechange",e="onload",E="createElement",I=!1,B,z={},K={},J=/^\/|^[^:]*:\/\//,n=/url\s*\(['"]?([^'"\)]*)['"]?\)/g,C=i.document,t;if(C)t=C.head||(C.head=C.getElementsByTagName("head")[0]);var G,u,H;define("css",{normalize:function(b,
e){var g,j;if(!b)return b;g=b.split(",");j=[];for(var i=0,n=g.length;i<n;i++)j.push(e(g[i]));return j.join(",")},load:function(f,e,g,i){function n(){--u==0&&setTimeout(function(){g(x(d.sheet||d.styleSheet))},0)}var s=(f||"").split(","),u=s.length;if(f)for(var m=s.length-1,w;m>=0;m--,w=!0){var f=s[m],f=b(f),a=f.shift(),a=e.toUrl(a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".css":a),d=j(C),v={link:d,url:a,wait:i.cssWatchPeriod||50};("nowait"in f?f.nowait!="false":i.cssDeferLoad)?g(x(d.sheet||d.styleSheet)):
A(v,n);d.href=a;w?t.insertBefore(d,z[w].previousSibling):t.appendChild(d);z[a]=d}else g({translateUrls:function(a,b){var d;d=e.toUrl(b);d=d.substr(0,d.lastIndexOf("/")+1);return o(a,d)},injectStyle:function(a){return r(a)},proxySheet:function(a){if(a.sheet)a=a.sheet;return x(a)}})},"plugin-builder":"./builder/css"})})(this);
define("jq",["js"],function(){return{load:function(i,g,b){function j(g){typeof b.resolve=="function"?b.resolve(g):b(g)}typeof jQuery!="undefined"?j(jQuery):g(["js!"+i],function(){typeof jQuery!="undefined"?j(jQuery):typeof b.reject=="function"&&b.reject("jQuery NOT defined!")})}}});
define("foscss",["css"],function(){return{load:function(i,g,b){if(typeof $sf.skin!="undefined"&&$sf.skin!="fos")i="css!"+i;else switch(parseInt($sf.plabel)){case 1:i="css!starfield/sf.fos.core.1.css";break;case 2:i="css!starfield/sf.fos.core.2.css";break;case 1387:i="css!starfield/sf.fos.core.1387.css";break;default:i="css!starfield/sf.fos.core.0.css"}g([i],function(g){typeof g!="undefined"?typeof b.resolve=="function"?b.resolve(g):b(g):typeof b.reject=="function"&&b.reject("CSS NOT defined!")})}}});
define("i18n",["curl"],function(i){return{load:function(g,b,j){function w(b){typeof j.reject=="function"&&j.reject(b)}function v(b,i){if(y.length>1&&typeof i=="object")for(var r in i)b[r]=i[r];typeof b!="undefined"?typeof j.resolve=="function"?j.resolve(b):j(b):w("i18n failed on "+g)}function A(){y.length>1?(y.pop(),i(y).then(v,A)):w("i18n cannot find "+g)}var y=[g];$sf.culture!="en"&&(b=g.lastIndexOf("/"),y.push(g.substr(0,b)+"/"+$sf.culture+"/"+g.substr(b+1)));i(y).then(v,A)}}});
$sf.preload>=1&&require("css!starfield/sf.core.css");$sf.preload>=2&&require("starfield/sf.core.pkg");$sf.plabel!=1&&require("domReady!",function(){document.body.className+=(document.body.className==""?"":" ")+"sf-pl"});
